name: main

on:
  workflow_dispatch:
    inputs:
      config_file:
        required: true
        type: string
        description: config file (required)
      docker_image_tag:
        required: false
        type: string
        description: docker image file (option)
        default: latest

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.token }}
    steps:
      - uses: actions/checkout@v4

      - run: |
          config_file="./cron_test_config/${{ github.event.inputs.config_file }}"
          echo "config_file=$config_file" >> $GITHUB_ENV

          chmod +x ./.github/scripts/exec_400.sh
          chmod +x ./.github/scripts/exec_420.sh

      - run: |
          if [[ ${{ github.event.inputs.docker_image_tag }} = latest ]]; then
            ./.github/scripts/exec_400.sh ${{ env.GITHUB_TOKEN }} ${{ env.config_file }}
            docker_image_tag=$(cat docker_image_tag)
          else
            docker_image_tag=${{ github.event.inputs.docker_image_tag }}
          fi
          echo "docker_image_tag=$docker_image_tag" >> $GITHUB_ENV

      - run: |
          ./.github/scripts/exec_420.sh ${{ env.GITHUB_TOKEN }} ${{ env.config_file }} ${{ env.docker_image_tag }}
